import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    content: {
        flex: 100,
        backgroundColor: '#121212',
        width: '100%',
        height: '100%',
    },
    container: {
        marginLeft: '8%',
        marginRight: '8%',
    },
    topContainer: {
        flex: 20,
        backgroundColor: '#272727',
        width: '100%',
        height: '100%',
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
    },
    middleContainer: {
        flex: 70,
        backgroundColor: '#000000',
        width: '100%',
        height: '100%',
        paddingBottom: '10%',
        paddingTop: '10%',
    },
    bottomContainer: {
        flex: 10,
        backgroundColor: '#272727',
        width: '100%',
        height: '100%',
        borderBottomLeftRadius: 25,
        borderBottomRightRadius: 25,
    },
    contentImg: {
        flex: 30,
    },
    title: {
        fontSize: 30,
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#47D704',
        marginTop: '-30%',
    },
    subtitle: {
        fontSize: 14,
        fontStyle: 'normal',
        width: '100%',
        textAlign: 'left',
        color: '#FFFFFF',
        marginBottom: '5%',
        marginTop: '15%',
    },
    basicText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: 'normal',
        textAlign: 'center',
        marginRight: '5%',
        marginTop: '10%',
    },
    tinyText: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: 'normal',
        textAlign: 'center',
        marginTop: '1%',
        marginRight: '5%',
        marginLeft: '5%',
    },
    centeredContent: {
        alignSelf: 'center',
        textAlign: 'center',
    },
    sectionBtn: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'normal',
        textAlign: 'center',
        marginTop: '2%',
        marginBottom: '0%',
        borderWidth: 1,
        borderColor: '#fff',
        marginRight: '4%',
        marginLeft: '4%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.1)',
    },
    settingsIcon: {
        flex: 1,
        width: null,
        height: 50,
        marginTop: '5%',
        marginLeft: '10%',
        resizeMode: 'contain',
    },
    navIcon: {
        width: 50,
        height: 50,
        marginBottom: '2%',
        marginLeft: '3%',
        marginRight: '3%',
        resizeMode : 'cover',
    },
    searchBar: {
        height: 15,
        width: 50,
        resizeMode: 'cover',
    }
});
